language: ruby
bundler_args: --binstubs --jobs=3 --retry=3
cache: bundler
sudo: false
before_install:
  - gem i rubygems-update -v '<3' && update_rubygems
  # from travis docs, to use bundler 1.x:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
before_script:
  - "bin/ci-code-review"
script: bin/ci
rvm:
  - 2.5.0
env:
  - RAILS_VERSION='~> 5.2.0'
  - RAILS_VERSION='~> 5.1.0'
  - RAILS_VERSION='5-1-stable'
  - RAILS_VERSION='5-2-stable'
matrix:
  include:
    - rvm: 2.2.3
      env: RAILS_VERSION='~> 5.1.0'
    - rvm: 2.4.4
      env: RAILS_VERSION='~> 4.2.10'
  fast_finish: true
