language: ruby
bundler_args: --binstubs --jobs=3 --retry=3
cache: bundler
sudo: false
before_install:
  - gem update --system
  - gem install bundler
before_script:
  - "bin/ci-code-review"
script: bin/ci
rvm:
  - 2.6
  - 2.7
env:
  - RAILS_VERSION='~> 5.2.0'
  - RAILS_VERSION='5-2-stable'
matrix:
  fast_finish: true
